name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  make:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make 
      run:  make Build -C 3_Implementation
